clear; close all;

% These error coefficients were computed with Mathematica using the 
% methodology described in the paper, Sect. 3.5.  We simply plot them here.
% The schemes were generated by the script generate_optimized_domains.m,
% then the error terms computed from the resulting stability polynomial for
% each method.
cores4 = 2:8;
cores8 = 3:11;
cores12 = 4:10;
cores16 = 5:9;

p4 = [1.040e-3, 3.462e-4,  1.741e-4,  1.049e-4,  7.010e-5,  5.023e-5,  4.330e-5];
p8 = [1.340e-9, 2.931e-8, 7.097e-9, 2.376e-9, 9.740e-10, 4.599e-10, 2.411e-10, 1.360e-10, 9.878e-11];
p12 = [2.112e-13, 3.725e-14, 4.823e-14, 9.770e-15, 2.638e-15, 8.580e-16, 5.058e-16];
p16 = [4.842e-18, 1.733e-18, 1.376e-19, 1.779e-22, 3.517e-21];

fig = figure;
ax = getax(fig);
xlimits = [-.2 12.4];
ylimits = [10^-23 10^0];
orders = [4 8 12 16];
markers = {':v',':s',':^',':o'};
colors = linecolors();
linewidth = 1.4;

semilogy(cores4,p4,markers{1},'LineWidth',linewidth,'Color',colors(1,:)); hold on;
semilogy(cores8,p8,markers{2},'LineWidth',linewidth,'Color',colors(2,:)); hold on;
semilogy(cores12,p12,markers{3},'LineWidth',linewidth,'Color',colors(3,:)); hold on;
semilogy(cores16,p16,markers{4},'LineWidth',linewidth,'Color',colors(4,:)); hold on;
semilogy(1,8.333e-3,'*','LineWidth',linewidth,'Color',colors(5,:));  % RK4
semilogy(1,3.602e-9,'x','LineWidth',linewidth,'Color',colors(6,:));  % RK8

axis(ax,[xlimits ylimits]);

pos = get(ax,'Position');
makedim = @(x,y)[(x - min(xlimits))/diff(xlimits) * pos(3) + pos(1) + .007, ...
                 (log(y) - log(min(ylimits)))/diff(log(ylimits)) * pos(4) + pos(2) - .0365, ...
                 0.065 0.065];
makeannot = @(x,y,str)annotation('textbox',makedim(x,y),'String',str,...
                 'FitBoxToText','on','BackgroundColor',[1 1 1], ...
                 'EdgeColor','none','FaceAlpha',0,'FontSize',12);
makeannot(cores4(end),p4(end),'GBS_4');
makeannot(cores8(end),p8(end),'GBS_8');
makeannot(cores12(end),p12(end),'GBS_{12}');
makeannot(cores16(end),p16(end),'GBS_{16}');

makeannot(1-.065,8.333e-3,'RK_4');
makeannot(1-.065,3.602e-9,'RK_8');
    
grid on;
ax.FontSize = 10;
h = xlabel('Number of Cores'); h.FontSize = 12;
h = ylabel('Leading Order Error Coefficient'); h.FontSize = 12;
set(ax,'xtick',1:11)
set(fig,'Color','w');

paper_export_fig(ax,'leading_error',1);

function ax = getax(fig)
    ax = findall(fig,'type','axes');
    if length(ax)>1
        ax = ax(1);
    end
    if isempty(ax)
        ax = axes(fig);
    end
end
